name: Publish executables

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        include:
          - os: windows-latest
            executable_name: examples/keyring-cli.exe
            posted_name: keyring-cli.windows.exe
          - os: macos-latest
            executable_name: examples/keyring-cli
            posted_name: keyring-cli.macos
          - os: ubuntu-latest
            executable_name: examples/keyring-cli
            posted_name: keyring-cli.linux

    steps:
      - name: Fetch head
        uses: actions/checkout@v5

      - name: Install rust stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release --features=apple-native,windows-native,linux-native --example keyring-cli

      - name: Post keyring-cli executable
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.executable_name }}
          asset_name: ${{ matrix.posted_name }}
          tag: ${{ github.ref }}
